name: gradiend
metric: pearson
model_config:
  lr: 1e-5
  epochs: 100
  max_iterations: 5000
  source: "inv_gradient"
  multi_task: False
  shared: False
  eval_max_size: 500
  n_evaluation: 500
  seed: 42
  num_dims: 1
  batch_size: 32
  accumulation_steps: 1